version: "3.8"

services:
  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfiles/express.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./packages/backend:/express-server
    env_file:
      - .env
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./pg-db:/var/lib/postgresql/data
  admin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports: 
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
